### ISSUE TITLE
Always offer "master" as continuous build

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/easyrpg.org#49]
When the stable branch was the last one that was built the continuous build will give stable builds.
This can lead to bogus bug reports because the result of the download link will be random.

Instead of linking to jenkins directly this will need a ajax request to

```https://ci.easyrpg.org/view/Player/job/$JOBNAME/lastSuccessfulBuild/api/json?tree=actions[buildsByBranchName[*[*]]]```

``buildsByBranchName -> origin/master`` contains the job ID that can be inserted in the URL to get the correct artifact.

Replace e.g. ``https://ci.easyrpg.org/job/player-linux/lastSuccessfulBuild/artifact/easyrpg-player-static.tar.gz`` with ``download_latest("player-linux", "easyrpg-player-static.tar.gz")``

**Comment by carstene1ns** [comment]
We could also apply the link once a day with the regular website update.

**Comment by Ghabry** [comment]
Oh right we have this page generator :D.
Also a good idea. Just use nanoc to do the requests.

**Comment by carstene1ns** [comment]
I think we should just fix this from the jenkins builds themselves. Copy the artifact like we do for the emscripten pull request builds.
Then the links will be cleaner and stay valid, even if jenkins configuration (number of builds/kept artifacts/branch config) changes.

**Comment by carstene1ns** [comment]
Fixed by #50.
