### ISSUE TITLE
Remove extra s from directory in translation guide

### ISSUE THREAD

**Issue by ElTipejoLoco** [EasyRPG/easyrpg.org#96]
As evidenced in the Player's [current translation.cpp code](https://github.com/EasyRPG/Player/blob/ad6e8232bf51b804537fd603fc77a6c2770d4254/src/translation.cpp#L175), the [game translation guide](https://github.com/EasyRPG/easyrpg.org/blob/da54e357856c8a9739c588c780fbcc1021256292/content/player/guide/game_translation.md?plain=1#L102) should not suggest `Language/LANGUAGE_NAME/Fonts` as a directory, but instead `Language/LANGUAGE_NAME/Font` to avoid confusing translators.

**Comment by Mimigris** [comment]
Thank you for reporting this, it seems to be a typo or a leftover from a development version similar to how the `language` folder was called `languages`, will fix it with #93
